@echo off
set BUCKET_NAME="%%BUCKET_NAME%%"
set OBJECT_NAME="%%OBJECT_NAME%%"
set S3_ENDPOINT_URL="%%S3_ENDPOINT_URL%%"
aws s3 cp --endpoint-url=%S3_ENDPOINT_URL% %%INPUT_FILE%% s3://%BUCKET_NAME%/%OBJECT_NAME%
