#!/bin/sh
export BUCKET_NAME="%%BUCKET_NAME%%"
export OBJECT_NAME="%%OBJECT_NAME%%"
export S3_ENDPOINT_URL="%%S3_ENDPOINT_URL%%"
aws s3 cp --endpoint-url=$S3_ENDPOINT_URL %%INPUT_FILE%% s3://$BUCKET_NAME/$OBJECT_NAME
